# Generated by Django 3.2.8 on 2021-10-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('igiti', 'igiti'), ('akarere', 'akarere')], max_length=100),
        ),
    ]
