# Generated by Django 3.2.8 on 2021-11-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_productgallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('size', 'size'), ('igiti', 'igiti'), ('ibyo_gusiga', 'ibyo_gusiga')], max_length=100),
        ),
    ]
