# Generated by Django 3.2.8 on 2022-01-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220125_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
