# Generated by Django 3.2.8 on 2022-01-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('cellID', models.IntegerField(primary_key=True, serialize=False)),
                ('cellname', models.CharField(max_length=100)),
                ('sectorID', models.IntegerField()),
                ('districtCode', models.IntegerField()),
                ('provincecode', models.IntegerField()),
            ],
            options={
                'db_table': 'celltable',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('districtCode', models.IntegerField(primary_key=True, serialize=False)),
                ('districtname', models.CharField(max_length=100)),
                ('provincecode', models.IntegerField()),
            ],
            options={
                'db_table': 'districttable',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('provincecode', models.IntegerField(primary_key=True, serialize=False)),
                ('provincename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'provincetable',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sectorID', models.IntegerField(primary_key=True, serialize=False)),
                ('sectorname', models.CharField(max_length=100)),
                ('districtCode', models.IntegerField()),
                ('provincecode', models.IntegerField()),
            ],
            options={
                'db_table': 'sectortable',
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('villageID', models.IntegerField(primary_key=True, serialize=False)),
                ('villagename', models.CharField(max_length=100)),
                ('cellID', models.IntegerField()),
                ('sectorID', models.IntegerField()),
                ('districtCode', models.IntegerField()),
                ('provincecode', models.IntegerField()),
            ],
            options={
                'db_table': 'villagetable',
            },
        ),
    ]
